#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py makemigrations
python manage.py migrate
python manage.py parse_data airport data/airport-codes_csv.csv
python manage.py parse_data flight data/flighdata_B.csv
python manage.py parse_data segment data/flighdata_B_segments.csv
python manage.py runserver 0.0.0.0:8000