# Generated by Django 3.1.2 on 2020-10-22 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('continent', models.CharField(max_length=2)),
                ('iso_country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('out_flight_no', models.CharField(max_length=32)),
                ('out_depart_date', models.DateField(blank=True, null=True)),
                ('out_depart_time', models.TimeField(blank=True, null=True)),
                ('out_arrival_date', models.DateField(blank=True, null=True)),
                ('out_arrival_time', models.TimeField(blank=True, null=True)),
                ('out_booking_class', models.CharField(max_length=256, null=True)),
                ('out_flight_class', models.CharField(max_length=64)),
                ('out_carrier_code', models.CharField(max_length=2, null=True)),
                ('in_flight_no', models.CharField(max_length=32)),
                ('in_depart_date', models.DateField(blank=True, null=True)),
                ('in_depart_time', models.TimeField(blank=True, null=True)),
                ('in_arrival_date', models.DateField(blank=True, null=True)),
                ('in_arrival_time', models.TimeField(blank=True, null=True)),
                ('in_booking_class', models.CharField(max_length=256, null=True)),
                ('in_flight_class', models.CharField(max_length=64)),
                ('in_carrier_code', models.CharField(max_length=2, null=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('original_currency', models.CharField(max_length=3)),
                ('reservation', models.CharField(max_length=32)),
                ('carrier', models.CharField(max_length=64)),
                ('oneway', models.BooleanField()),
                ('dep_air', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_air_airport', to='flight_data.airport')),
                ('dest_air', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_air_airport', to='flight_data.airport')),
                ('in_arrive_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_arrive_code_airport', to='flight_data.airport')),
                ('in_depart_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_depart_code_airport', to='flight_data.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_date', models.DateField(blank=True, null=True)),
                ('arr_date', models.DateField(blank=True, null=True)),
                ('dep_time', models.TimeField(blank=True, null=True)),
                ('arr_time', models.TimeField(blank=True, null=True)),
                ('dep_terminal', models.CharField(max_length=32, null=True)),
                ('arr_terminal', models.CharField(max_length=32, null=True)),
                ('flight_no', models.CharField(max_length=32)),
                ('journey', models.CharField(choices=[('out', 'Out'), ('in', 'In')], default='out', max_length=3)),
                ('seg_class', models.CharField(max_length=64)),
                ('booking_class', models.CharField(max_length=256, null=True)),
                ('arr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arr_code_airport', to='flight_data.airport')),
                ('dep_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_code_airport', to='flight_data.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_data.flight')),
            ],
        ),
    ]
